services:
  web:
    build: .
    volumes:
      - .:/repository
    networks:
      - web
    environment:
      - WEB_DB_DIALECT=${WEB_DB_DIALECT}
      - WEB_DB_HOST=${WEB_DB_HOST}
      - WEB_DB_PORT=${WEB_DB_PORT}
      - WEB_DB_USER=${WEB_DB_USER}
      - WEB_DB_PASSWORD=${WEB_DB_PASSWORD}
      - WEB_DB_NAME=${WEB_DB_NAME}
    ports:
      - "${WEB_APP_PORT}:8000"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - web
networks:
  web:
    driver: bridge